#ifndef _TETRIS_H_INCLUDED_
	#define _TETRIS_H_INCLUDED_
const TETRIS_ENTITY_ENUM tetris_drop[NUM_TETRIMINOS][5][5] =
{
	{ // "I" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_I,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_I,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_I,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_I,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "T" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_T,		TETRIS_ENTITY_T,		TETRIS_ENTITY_T,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_T,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "L" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_L,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_L,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_L,		TETRIS_ENTITY_L,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "Negative L" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_N_L,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_N_L,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_N_L,		TETRIS_ENTITY_N_L,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "O" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_O,		TETRIS_ENTITY_O,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_O,		TETRIS_ENTITY_O,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "S" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_S,		TETRIS_ENTITY_S,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_S,		TETRIS_ENTITY_S,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "Z" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_Z,		TETRIS_ENTITY_Z,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_Z,		TETRIS_ENTITY_Z,		TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "Single" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "Double" Bock
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // Tilt Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_SINGLE,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	},
	{ // "Bomb" Block
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_BOMB,		TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING},
		{TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING,	TETRIS_ENTITY_NOTHING}
	}
};
#endif